const STORAGE = {
  tubemod_version: "1.13.2",
  tubemod_elements: [
    {
      id: "scheduled-videos",
      selector:
        "//ytd-rich-item-renderer[.//ytd-thumbnail-overlay-time-status-renderer[@overlay-style='UPCOMING']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "live-videos",
      selector:
        "//ytd-rich-item-renderer[.//div[@id='meta']/ytd-badge-supported-renderer[not(@hidden)]]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "video-previews",
      selector: "//div[@id='video-preview' or @id='mouseover-overlay'] | //animated-thumbnail-overlay-view-model",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "card-colored-background",
      selector: "//yt-touch-feedback-shape",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "video-thumbnails",
      selector: "//yt-thumbnail-view-model | //div[@id = 'thumbnail'] | //a[@class='yt-lockup-view-model__content-image']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "video-thumbnails-blur",
      selector:
        "//ytd-thumbnail//yt-image | //ytd-playlist-thumbnail | //yt-thumbnail-view-model/div",
      checked: false,
      styles: {
        filter: "blur(15px)",
        overflow: "hidden",
      },
      pageTypes: [],
    },
    {
      id: "lowercase-title",
      selector:
        "//ytd-watch-metadata//div[@id='title'] | //*[@id='video-title'] | //yt-lockup-metadata-view-model/div/h3/a/span | //ytm-shorts-lockup-view-model/div/div/h3/a/span",
      checked: false,
      property: TEXT_TRANSFORM,
      style: LOWERCASE,
      pageTypes: [],
    },
    {
      id: "video-meta-data",
      selector: "//div[@id='metadata-line'] | //div[@class='yt-content-metadata-view-model__metadata-row'][span[@class='yt-content-metadata-view-model__delimiter']] | //div[contains(@class, 'shortsLockupViewModelHostMetadataSubhead')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "download-badge",
      selector: "//p[text()[contains(., 'Downloaded')]]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.DOWNLOADS],
    },
    {
      id: "logo",
      selector: "//ytd-topbar-logo-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "search-bar",
      selector: "//ytd-searchbox[@id='search'] | //yt-searchbox",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "microphone-search",
      selector: "//*[@id='voice-search-button']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "create",
      selector:
        "//div[@id='buttons' and contains(@class, 'ytd-masthead')]/ytd-button-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "notifications",
      selector: "//ytd-notification-topbar-button-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "studio-button",
      selector: "//ytd-notification-topbar-button-renderer",
      checked: false,
      pageTypes: [],
    },
    {
      id: "profile-google-account",
      selector: "//ytd-compact-link-renderer[contains(., 'Google Account')] | //ytd-compact-link-renderer/a[contains(@href, 'accounts.google.com')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-switch-account",
      selector: "//ytd-compact-link-renderer[contains(., 'Switch account')] | //ytd-compact-link-renderer[contains(., 'Cambiar cuenta')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-youtube-studio",
      selector: "//ytd-compact-link-renderer[contains(., 'YouTube Studio')] | //ytd-compact-link-renderer/a[contains(@href, 'studio.youtube.com')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-purchases-memberships",
      selector: "//ytd-compact-link-renderer[contains(., 'Purchases and memberships')] | //ytd-compact-link-renderer[contains(., 'Compras y suscripciones')] | //ytd-compact-link-renderer/a[contains(@href, '/paid_memberships')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-your-data",
      selector: "//ytd-compact-link-renderer[contains(., 'Your data in YouTube')] | //ytd-compact-link-renderer[contains(., 'Tus datos en YouTube')] | //ytd-compact-link-renderer/a[contains(@href, '/account') and contains(., 'data')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-appearance",
      selector: "//ytd-compact-link-renderer[contains(., 'Appearance')] | //ytd-compact-link-renderer[contains(., 'Apariencia')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-language",
      selector: "//ytd-compact-link-renderer[contains(., 'Display language')] | //ytd-compact-link-renderer[contains(., 'Idioma')] | //ytd-compact-link-renderer[contains(., 'Idioma de visualización')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-restricted-mode",
      selector: "//ytd-compact-link-renderer[contains(., 'Restricted Mode')] | //ytd-compact-link-renderer[contains(., 'Modo restringido')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-location",
      selector: "//ytd-compact-link-renderer[contains(., 'Location')] | //ytd-compact-link-renderer[contains(., 'Ubicación')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-keyboard-shortcuts",
      selector: "//ytd-compact-link-renderer[contains(., 'Keyboard shortcuts')] | //ytd-compact-link-renderer[contains(., 'Atajos de teclado')] | //ytd-compact-link-renderer/a[contains(@href, 'keyboard_shortcuts')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-settings",
      selector: "//ytd-compact-link-renderer[contains(., 'Settings') and not(contains(., 'Appearance'))] | //ytd-compact-link-renderer[contains(., 'Configuración') and not(contains(., 'Apariencia'))] | //ytd-compact-link-renderer/a[contains(@href, '/account') and contains(., 'Settings')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-help",
      selector: "//ytd-compact-link-renderer[contains(., 'Help')] | //ytd-compact-link-renderer[contains(., 'Ayuda')] | //ytd-compact-link-renderer/a[contains(@href, '/help')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-send-feedback",
      selector: "//ytd-compact-link-renderer[contains(., 'Send feedback')] | //ytd-compact-link-renderer[contains(., 'Enviar comentarios')] | //ytd-compact-link-renderer/a[contains(@href, 'feedback')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "profile-sign-out",
      selector: "//ytd-compact-link-renderer/a[@href='/logout']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "sidebar",
      selector:
        "//tp-yt-app-drawer | //ytd-mini-guide-renderer | //yt-icon-button[@id='guide-button']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "home",
      selector:
        "//ytd-guide-entry-renderer[a[@href='/']] | //ytd-mini-guide-entry-renderer[a[@href='/']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "shorts",
      selector:
        "//ytd-guide-entry-renderer[a[@title='Shorts']] | //ytd-mini-guide-entry-renderer[a[@title='Shorts']] | //ytd-guide-entry-renderer[a[@title='YouTube Shorts']] | //ytd-mini-guide-entry-renderer[a[@title='YouTube Shorts']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "subscriptions-panel",
      selector: "(//ytd-guide-section-renderer)[2]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "subscriptions",
      selector:
        "//ytd-guide-entry-renderer[a[@href='/feed/subscriptions']] | //ytd-mini-guide-entry-renderer[a[@href='/feed/subscriptions']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "subscriptions-panel-new-indicator",
      selector:
        "//ytd-guide-entry-renderer[@line-end-style='dot']//div[@id='newness-dot']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "subscriptions-panel-live-indicator",
      selector:
        "//yt-icon/span/div/svg/path[@d='M4.222 4.223a11 11 0 000 15.555 1 1 0 101.414-1.414 9 9 0 010-12.727 1 1 0 10-1.414-1.414Zm13.79.353a1 1 0 000 1.414 8.5 8.5 0 010 12.022 1 1 0 001.413 1.414 10.501 10.501 0 000-14.85 1 1 0 00-1.413 0Zm-2.83 2.827a1 1 0 000 1.414 4.501 4.501 0 010 6.365 1.001 1.001 0 001.414 1.414 6.5 6.5 0 000-9.193 1 1 0 00-1.415 0Zm-7.78 0a6.5 6.5 0 000 9.194 1 1 0 001.415-1.415 4.5 4.5 0 010-6.364 1.001 1.001 0 00-1.415-1.415ZM12 10a2 2 0 100 4 2 2 0 000-4Z']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "you-panel",
      selector: "(//ytd-guide-section-renderer)[3]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "you",
      selector:
        "//ytd-guide-entry-renderer[@id ='header-entry'][a[@href='/feed/you']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "history",
      selector: "//ytd-guide-entry-renderer[a[@href='/feed/history']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "playlists",
      selector: "//ytd-guide-entry-renderer[a[@href='/feed/playlists']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "watch-later",
      selector: "//ytd-guide-entry-renderer[a[@href='/playlist?list=WL']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "liked-videos",
      selector: "//ytd-guide-entry-renderer[a[@href='/playlist?list=LL']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "my-videos",
      selector:
        "//ytd-guide-entry-renderer[a[starts-with(@href, 'https://studio.youtube.com/channel')]]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "you-downloads",
      selector:
        "//div[@id='section-items']/ytd-guide-downloads-entry-renderer  | //ytd-mini-guide-entry-renderer[a[@href='/feed/downloads']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "my-clips",
      selector: "//ytd-guide-entry-renderer[a[@href='/feed/clips']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "your-movies-and-tv",
      selector:
        "//ytd-guide-entry-renderer[a[@href='/feed/storefront?bp=ogUCKAQ%3D']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "your-podcasts",
      selector: "//ytd-guide-entry-renderer[a[@href='/feed/podcasts']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "courses",
      selector: "//ytd-guide-entry-renderer[a[@href='/feed/courses']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
/*     {
      id: "you-show-more-less",
      selector: "//ytd-guide-entry-renderer[a[@href='/feed/courses']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    }, */
    {
      id: "explore-panel",
      selector: "(//ytd-guide-section-renderer)[4]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "more-from-youtube-panel",
      selector: "(//ytd-guide-section-renderer)[5]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
     {
      id: "youtube-premium",
      selector:
        "//ytd-guide-entry-renderer[a[@href='/premium']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    }, 
    {
      id: "youtube-studio",
      selector:
        "//ytd-guide-entry-renderer[a[@href='https://studio.youtube.com/']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "youtube-music",
      selector:
        "//ytd-guide-entry-renderer[a[@href='https://music.youtube.com/']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
  {
      id: "youtube-kids",
      selector:
        "//ytd-guide-entry-renderer[a[@href='https://www.youtubekids.com/?source=youtube_web']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "settings-panel",
      selector: "(//ytd-guide-section-renderer)[6]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "youtube-footer",
      selector: "//ytd-guide-renderer/div[@id='footer']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [],
    },
    {
      id: "tabs",
      selector:
        "//ytd-feed-filter-chip-bar-renderer[@component-style='FEED_FILTER_CHIP_BAR_STYLE_TYPE_DEFAULT']/..",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "ads",
      selector:
        "//ytd-ad-slot-renderer/ancestor::ytd-rich-item-renderer | //*[@id='player-ads'] | //ytd-banner-promo-renderer/.. | //div[@id='masthead-ad']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "all-videos",
      selector: "//*[@page-subtype='home']/div[@id='primary']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "members-only",
      selector:
        "//ytd-rich-item-renderer[.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='M8 1C4.13 1 1 4.13 1 8s3.13 7 7 7 7-3.13 7-7-3.13-7-7-7Zm2.47 10.5L7.99 9.94 5.5 11.5l.67-2.97L4 6.5l2.87-.22L8.01 3.5l1.12 2.78L12 6.5 9.82 8.53l.65 2.97Z']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "home-posts",
      selector: "//ytd-rich-section-renderer[.//ytd-post-renderer]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "home-shorts",
      selector: "//ytd-rich-section-renderer[.//ytm-shorts-lockup-view-model]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "home-news",
      selector:
        "//ytd-rich-section-renderer[not(.//ytm-shorts-lockup-view-model) and not(.//div[contains(@class, 'button-container') and not(@hidden)][.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='m18 9.28-6.35 6.35-6.37-6.35.72-.71 5.64 5.65 5.65-5.65z']])]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "home-trending",
      selector:
        "//ytd-rich-section-renderer[.//div[contains(@class, 'button-container') and not(@hidden)][.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='m18 9.28-6.35 6.35-6.37-6.35.72-.71 5.64 5.65 5.65-5.65z']]]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "home-playables",
      selector:
        "//ytd-rich-section-renderer[.//a[contains(@href, '/playables')]]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "home-primetime-movies",
      selector: "//ytd-rich-section-renderer[.//a[@href='/feed/storefront']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "playlist-mix",
      selector:
        "//ytd-rich-item-renderer[.//ytd-playlist-thumbnail[not(@hidden)]] | //ytd-rich-item-renderer[.//a[contains(@href, 'start_radio=1')]]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "podcast-playlist",
      selector: "//ytd-rich-item-renderer[.//a[contains(@href, 'pp=')]]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "viewed-videos",
      selector:
        "//ytd-rich-item-renderer[.//div[@id='progress'][contains(@style, 'width: 100%')]]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "partially-viewed-videos",
      selector:
        "//ytd-rich-item-renderer[.//ytd-thumbnail[not(@is-live-video)]//div[@id='progress']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.HOME],
    },
    {
      id: "subscriptions-shorts",
      selector: "//ytd-rich-shelf-renderer/../.. | //ytd-rich-shelf-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.SUBSCRIPTIONS],
    },
    {
      id: "search-shorts",
      selector: "//ytd-reel-shelf-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.SEARCH],
    },
    {
      id: "search-people-also-searched",
      selector: "//div[@id='contents']/ytd-horizontal-card-list-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.SEARCH],
    },
    {
      id: "trending-shorts",
      selector: "//ytd-video-renderer[.//a[contains(@href, '/shorts')]]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.TRENDING],
    },
    {
      id: "channel-trailer",
      selector: "//*[@id='c4-player']",
      checked: false,
      pageTypes: [PAGE_TYPES.CHANNEL],
    },
    {
      id: "video-progress-bar-dot",
      selector: "//div[@class='ytp-scrubber-container']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-settings-playback-speed",
      selector:
        "//div[@role='menuitem'][.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='M12 1c1.44 0 2.87.28 4.21.83a11 11 0 0 1 3.45 2.27l-1.81 1.05A9 9 0 0 0 3 12a9 9 0 0 0 18-.00l-.01-.44a8.99 8.99 0 0 0-.14-1.20l1.81-1.05A11.00 11.00 0 0 1 10.51 22.9 11 11 0 0 1 12 1Zm7.08 6.25-7.96 3.25a1.74 1.74 0 1 0 1.73 2.99l6.8-5.26a.57.57 0 0 0-.56-.98Z']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-settings-sleep-timer",
      selector:
        "//div[@role='menuitem'][.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='M12.33 1.00C12.22 1.00 12.11 1.00 12 1C5.92 1 1 5.92 1 12C1 18.07 5.92 23 12 23C13.90 23.00 15.78 22.50 17.44 21.55C19.10 20.61 20.48 19.25 21.46 17.61L21.64 17.29C22.06 16.52 21.21 15.73 20.35 15.88C18.76 16.15 17.12 15.94 15.66 15.27C14.19 14.59 12.97 13.49 12.14 12.11C11.31 10.73 10.91 9.13 11.01 7.52C11.11 5.91 11.69 4.37 12.67 3.09L12.89 2.83C13.45 2.16 13.20 1.03 12.33 1.00ZM15.56 2.60C15.45 2.84 15.43 3.11 15.51 3.36C15.59 3.61 15.77 3.82 16.01 3.94C16.91 4.39 17.73 4.99 18.44 5.71L18.73 6.03L18.80 6.10C18.99 6.27 19.22 6.36 19.47 6.37C19.72 6.37 19.96 6.28 20.15 6.12C20.33 5.95 20.45 5.72 20.48 5.48C20.51 5.23 20.44 4.98 20.29 4.78L20.23 4.70L19.87 4.31C19.01 3.43 18.01 2.70 16.90 2.15C16.67 2.03 16.39 2.01 16.14 2.10C15.89 2.18 15.68 2.36 15.56 2.60M10.24 3.17C9.42 4.64 8.99 6.31 9 8C9 13.42 13.32 17.84 18.71 17.99C17.86 18.93 16.83 19.69 15.67 20.21C14.52 20.73 13.26 21.00 12 21C9.76 21.00 7.60 20.17 5.95 18.67C4.29 17.17 3.25 15.10 3.03 12.88C2.81 10.65 3.43 8.43 4.76 6.63C6.09 4.84 8.05 3.60 10.24 3.17M21.16 7.88C20.93 7.96 20.73 8.12 20.61 8.34C20.49 8.55 20.45 8.81 20.50 9.05L20.53 9.15L20.66 9.56C20.93 10.53 21.04 11.54 20.98 12.55C20.97 12.81 21.06 13.06 21.23 13.26C21.41 13.45 21.65 13.57 21.92 13.59C22.18 13.60 22.44 13.52 22.63 13.34C22.83 13.17 22.95 12.93 22.97 12.67C23.05 11.44 22.92 10.20 22.58 9.02L22.43 8.51L22.39 8.42C22.29 8.19 22.11 8.01 21.88 7.91C21.65 7.81 21.40 7.80 21.16 7.88Z']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-title",
      selector: "//div[@id='above-the-fold']/div[@id='title']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-subscribers",
      selector: "(//div[@id='upload-info'])[1]/yt-formatted-string",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-subscribe-button",
      selector: "//yt-button-shape[@id='subscribe-button-shape']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-subscribed-button",
      selector: "//div[@id='notification-preference-button']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-join-button",
      selector: "//div[@id='sponsor-button']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-likes-dislikes",
      selector: "//segmented-like-dislike-button-view-model",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-share",
      selector: "//div[@id='top-level-buttons-computed']/yt-button-view-model",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-download",
      selector: "//ytd-download-button-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-thanks",
      selector:
        "//div[@id='flexible-item-buttons']/yt-button-view-model[.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='M11 17h2v-1h1c.55 0 1-.45 1-1v-3c0-.55-.45-1-1-1h-3v-1h4V8h-2V7h-2v1h-1c-.55 0-1 .45-1 1v3c0 .55.45 1 1 1h3v1H9v2h2v1zm5.5-15c-1.74 0-3.41.88-4.5 2.28C10.91 2.88 9.24 2 7.5 2 4.42 2 2 4.64 2 7.99c0 4.12 3.4 7.48 8.55 12.58L12 22l1.45-1.44C18.6 15.47 22 12.11 22 7.99 22 4.64 19.58 2 16.5 2zm-3.75 17.85-.75.74-.74-.73-.04-.04C6.27 14.92 3 11.69 3 7.99 3 5.19 4.98 3 7.5 3c1.4 0 2.79.71 3.71 1.89L12 5.9l.79-1.01C13.71 3.71 15.1 3 16.5 3 19.02 3 21 5.19 21 7.99c0 3.7-3.28 6.94-8.25 11.86z']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-save",
      selector:
        "//div[@id='flexible-item-buttons']/yt-button-view-model[.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='M18 4v15.06l-5.42-3.87-.58-.42-.58.42L6 19.06V4h12m1-1H5v18l7-5 7 5V3z']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-clip",
      selector:
        "//div[@id='flexible-item-buttons']/yt-button-view-model[.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='M8 7c0 .55-.45 1-1 1s-1-.45-1-1 .45-1 1-1 1 .45 1 1zm-1 9c-.55 0-1 .45-1 1s.45 1 1 1 1-.45 1-1-.45-1-1-1zm3.79-7.77L21 18.44V20h-3.27l-5.76-5.76-1.27 1.27c.19.46.3.96.3 1.49 0 2.21-1.79 4-4 4s-4-1.79-4-4 1.79-4 4-4c.42 0 .81.08 1.19.2l1.37-1.37-1.11-1.11C8 10.89 7.51 11 7 11c-2.21 0-4-1.79-4-4s1.79-4 4-4 4 1.79 4 4c0 .43-.09.84-.21 1.23zm-.71.71-.43-.44.19-.58c.11-.34.16-.64.16-.92 0-1.65-1.35-3-3-3S4 5.35 4 7s1.35 3 3 3c.36 0 .73-.07 1.09-.21l.61-.24.46.46 1.11 1.11.71.71-.71.71-1.37 1.37-.43.43-.58-.18C7.55 14.05 7.27 14 7 14c-1.65 0-3 1.35-3 3s1.35 3 3 3 3-1.35 3-3c0-.38-.07-.75-.22-1.12l-.25-.61.47-.47 1.27-1.27.71-.71.71.71L18.15 19H20v-.15l-9.92-9.91zM17.73 4H21v1.56l-5.52 5.52-2.41-2.41L17.73 4zm.42 1-3.67 3.67 1 1L20 5.15V5h-1.85z']]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-collapsed-buttons",
      selector:
        "//div[@id='top-row']//ytd-menu-renderer//yt-button-shape[@id='button-shape']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "stream-show-chat",
      selector: "//div[@id='show-hide-button']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-description",
      selector: "//div[@id='description-inner']/parent::div",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-views",
      selector:
        "//div[@id='view-count'] | (//yt-formatted-string[@id='info']/span)[position()<3]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-people-mentioned-description",
      selector: "//yt-video-attributes-section-view-model",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-chapters-description",
      selector:
        "//ytd-horizontal-card-list-renderer[contains (@class, 'ytd-structured-description-content-renderer')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-shorts-description",
      selector:
        "//ytd-structured-description-content-renderer//ytd-reel-shelf-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-transcription-description",
      selector: "//ytd-video-description-transcript-section-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-channel-links-description",
      selector: "//ytd-video-description-infocards-section-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-live-chat-replay",
      selector: "//div[@id='teaser-carousel']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-summary-ai-generated",
      selector: "//div[@id='expandable-metadata']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-comments",
      selector: "//ytd-comments[@id='comments']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-comments-avatars",
      selector: "//div[@id='author-thumbnail']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-comments-replies",
      selector: "//ytd-comments[@id='comments']//div[@id='replies'] | //div[@class='continuation style-scope ytd-comment-view-model']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-categories-games",
      selector: "//ytd-rich-metadata-row-renderer/../..",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-ads",
      selector: "//div[@id='player-ads']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-offer-module",
      selector: "//div[@id='offer-module']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-tabs",
      selector: "//yt-related-chip-cloud-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-suggested-videos",
      selector:
        "//div[@class='ytp-fullscreen-grid'][//a[contains(@class, 'ytp-suggestion-set')]]/div[@class='ytp-fullscreen-grid-main-content']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-suggested-videos-new-badge",
      selector:
        "//div[contains(@class ,'yt-content-metadata-view-model__metadata-row--metadata-row-wrap')]",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-suggested-shorts",
      selector:
        "//div[@id='contents']/parent::ytd-item-section-renderer[contains(@class, 'watch-next')]//ytd-reel-shelf-renderer",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-suggestion-wall",
      selector: "//div[@class='ytp-endscreen-content']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-thumbnail",
      selector: "//ytd-watch-next-secondary-results-renderer/div[@id='items']",
      checked: false,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "youtube-progress-bar",
      selector: "//div[contains(@class,'ytp-play-progress')]",
      checked: false,
      property: BACKGROUND,
      style: YT_RED,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "video-progress-heat-map",
      selector: "//div[@class='ytp-heat-map-container']",
      checked: false,
      property: DISPLAY,
      style: DISPLAY_NONE,
      pageTypes: [PAGE_TYPES.VIDEO],
    },
    {
      id: "remove-rounded-borders",
      selector: "//body",
      checked: false,
      pageTypes: [],
    },
  ],
};

